### ISSUE TITLE
ETQ usager, j'ai accèss à une page "accueil de la démarche"/"Commencer la démarche" avant de me connecter

### ISSUE THREAD

**Issue by mfo** [demarches-simplifiees/demarches-simplifiees.fr#8957]
# TODO

- [ ] description -> quel est l'objet de cette démarche (en accordeon)
- [ ] a qui s'adresse la démarche, champs a ajouter
- [ ] lister les pieces justificatives

https://www.figma.com/file/YKcafywdYhT6ABFlmy5d56/Am%C3%A9lioration-vue-usagers?node-id=1-2&t=sInhnVIIFFL5Jsgn-0
