### ISSUE TITLE
ETQ instructeur, je souhaite pouvoir demander un avis d'expert via les actions multiples

### ISSUE THREAD

**Issue by mfo** [demarches-simplifiees/demarches-simplifiees.fr#9609]
tchak : 
> On pense à une action multiple sur les dossiers. Sélectionner plusieurs dossiers. Demander un avis à un ou plusieurs experts sur tous les dossiers sélectionnés. Le message et la pièce jointe sont les mêmes pour tous les avis envoyés.

# piste 0.1 d'implem
- [ ] ETQ instructeur, quand je suis sur la page des dossiers suivis, je peux cliquer sur un bouton "Demander un avis à un expert" (ds le sous menu autres action multiple). 
> <img width="993" alt="Screenshot 2024-01-22 at 9 08 07 AM" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/125964/7b51e809-30c6-4ad7-bb51-b708278d2e80">

- [ ] Ce ouvre une modal qui reprend l'écran le formulaire de demande d'avis. Ça intègre les 5 champs deja existant :
  - [ ] le ou les mails de(s) l'expert(s) a qui l'instructeur souhaite demander un avis qui equivaut a `avis.expert_id)`
  - [ ] le message d'introduction à(aux) expert(s) qui equivaut à `avis.introduction`
  - [ ] la question a(aux) expert(s) qui équivaut à `avis.question_label`
  - [ ] une PJ (optionnelle) qui équivaut a `avis.introduction_file`
  - [ ] si la demande d'avis est confidentielle qui équivaut `avis.confidentiel`
> ![Screenshot 2024-01-22 at 09-03-17 test · demarches-simplifiees fr](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/125964/07a2d261-cfbd-4c81-af6c-3b6ed17d6882)

- [ ] a la soumission du form, il faut ajouter l'action multiple demande d'avis

Et voila 🎉

**Comment by lisa-durand** [comment]
Je suis moyennement convaincue par ce changement de page / contexte du tableau. Le principe des actions multiples selon moi est qu'on reste dans le contexte du tableau et la ca fait quand mm un grand changement par rapport aux autres actions. Est-ce qu'on ne pourrait pas tenter un dropdown un peu plus gros ? Et voir si tout rentre dedans sans que ce soit trop ratatiné ? Dans ces cas la ca ferait 3 boutons : |Instruire des dossiers| |Demander un avis d'expert| |Autres actions multiples|

**Comment by mfo** [comment]
@lisa-durand , j'ai croisé la remonté de @dzc34. nouvelle proposition d'UI basé sur tes feedbacks
